INFO - 2025-01-20 13:16:38 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-01-20 13:16:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-01-20 13:57:30 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-01-20 13:57:30 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-01-20 13:58:08 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2025-01-20 13:58:23 --> ErrorException: Undefined variable $titulo
in APPPATH\Controllers\NuevoController.php on line 737.
 1 APPPATH\Controllers\NuevoController.php(737): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $titulo', 'C:\\xampp\\htdocs\\valoradorG2\\valorador\\app\\Controllers\\NuevoController.php', 737)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->mostrar_valoraciones_porDocente_porMateria3()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-01-20 16:33:34 --> mysqli_sql_exception: Operand should contain 1 column(s) in C:\xampp\htdocs\valoradorG2\valorador\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\valoradorG2\valorador\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `ac...', 0)
#1 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ac...')
#2 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ac...')
#3 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ac...', Array, false)
#4 C:\xampp\htdocs\valoradorG2\valorador\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\valoradorG2\valorador\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\valoradorG2\valorador\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\valoradorG2\valorador\app\Controllers\NuevoController.php(1160): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord('106')
#9 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
#10 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\valoradorG2\valorador\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2025-01-20 16:33:35 --> CodeIgniter\Database\Exceptions\DatabaseException: Operand should contain 1 column(s)
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (:id_otros_t:, :detalle_act_otros_tit:, :fecha:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\NuevoController.php(1160): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord('106')
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-01-20 16:33:35 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Operand should contain 1 column(s)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (34,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390814))')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (34,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390814))')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (:id_otros_t:, :detalle_act_otros_tit:, :fecha:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\NuevoController.php(1160): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord('106')
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-01-20 16:33:35 --> [Caused by] mysqli_sql_exception: Operand should contain 1 column(s)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (34,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390814))', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (34,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390814))')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (34,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390814))')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (:id_otros_t:, :detalle_act_otros_tit:, :fecha:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\NuevoController.php(1160): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord('106')
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-01-20 16:33:38 --> mysqli_sql_exception: Operand should contain 1 column(s) in C:\xampp\htdocs\valoradorG2\valorador\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\valoradorG2\valorador\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `ac...', 0)
#1 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ac...')
#2 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ac...')
#3 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ac...', Array, false)
#4 C:\xampp\htdocs\valoradorG2\valorador\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\valoradorG2\valorador\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\valoradorG2\valorador\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\valoradorG2\valorador\app\Controllers\NuevoController.php(1160): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord('106')
#9 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
#10 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\valoradorG2\valorador\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2025-01-20 16:33:38 --> CodeIgniter\Database\Exceptions\DatabaseException: Operand should contain 1 column(s)
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (:id_otros_t:, :detalle_act_otros_tit:, :fecha:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\NuevoController.php(1160): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord('106')
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-01-20 16:33:38 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Operand should contain 1 column(s)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (38,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390818))')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (38,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390818))')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (:id_otros_t:, :detalle_act_otros_tit:, :fecha:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\NuevoController.php(1160): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord('106')
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-01-20 16:33:38 --> [Caused by] mysqli_sql_exception: Operand should contain 1 column(s)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (38,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390818))', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (38,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390818))')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (38,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390818))')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (:id_otros_t:, :detalle_act_otros_tit:, :fecha:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\NuevoController.php(1160): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord('106')
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-01-20 16:33:38 --> mysqli_sql_exception: Operand should contain 1 column(s) in C:\xampp\htdocs\valoradorG2\valorador\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\valoradorG2\valorador\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `ac...', 0)
#1 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ac...')
#2 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ac...')
#3 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ac...', Array, false)
#4 C:\xampp\htdocs\valoradorG2\valorador\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\valoradorG2\valorador\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\valoradorG2\valorador\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\valoradorG2\valorador\app\Controllers\NuevoController.php(1160): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord('106')
#9 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
#10 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\valoradorG2\valorador\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2025-01-20 16:33:38 --> CodeIgniter\Database\Exceptions\DatabaseException: Operand should contain 1 column(s)
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (:id_otros_t:, :detalle_act_otros_tit:, :fecha:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\NuevoController.php(1160): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord('106')
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-01-20 16:33:38 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Operand should contain 1 column(s)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (38,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390818))')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (38,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390818))')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (:id_otros_t:, :detalle_act_otros_tit:, :fecha:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\NuevoController.php(1160): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord('106')
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-01-20 16:33:38 --> [Caused by] mysqli_sql_exception: Operand should contain 1 column(s)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (38,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390818))', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (38,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390818))')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (38,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390818))')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (:id_otros_t:, :detalle_act_otros_tit:, :fecha:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\NuevoController.php(1160): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord('106')
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-01-20 16:33:39 --> mysqli_sql_exception: Operand should contain 1 column(s) in C:\xampp\htdocs\valoradorG2\valorador\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\valoradorG2\valorador\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `ac...', 0)
#1 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ac...')
#2 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ac...')
#3 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ac...', Array, false)
#4 C:\xampp\htdocs\valoradorG2\valorador\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\valoradorG2\valorador\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\valoradorG2\valorador\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\valoradorG2\valorador\app\Controllers\NuevoController.php(1160): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord('106')
#9 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
#10 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\valoradorG2\valorador\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2025-01-20 16:33:39 --> CodeIgniter\Database\Exceptions\DatabaseException: Operand should contain 1 column(s)
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (:id_otros_t:, :detalle_act_otros_tit:, :fecha:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\NuevoController.php(1160): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord('106')
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-01-20 16:33:39 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Operand should contain 1 column(s)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (39,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390819))')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (39,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390819))')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (:id_otros_t:, :detalle_act_otros_tit:, :fecha:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\NuevoController.php(1160): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord('106')
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-01-20 16:33:39 --> [Caused by] mysqli_sql_exception: Operand should contain 1 column(s)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (39,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390819))', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (39,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390819))')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (39,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390819))')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (:id_otros_t:, :detalle_act_otros_tit:, :fecha:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\NuevoController.php(1160): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord('106')
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-01-20 16:33:39 --> mysqli_sql_exception: Operand should contain 1 column(s) in C:\xampp\htdocs\valoradorG2\valorador\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\valoradorG2\valorador\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `ac...', 0)
#1 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ac...')
#2 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ac...')
#3 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ac...', Array, false)
#4 C:\xampp\htdocs\valoradorG2\valorador\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\valoradorG2\valorador\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\valoradorG2\valorador\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\valoradorG2\valorador\app\Controllers\NuevoController.php(1160): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord('106')
#9 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
#10 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\valoradorG2\valorador\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2025-01-20 16:33:39 --> CodeIgniter\Database\Exceptions\DatabaseException: Operand should contain 1 column(s)
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (:id_otros_t:, :detalle_act_otros_tit:, :fecha:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\NuevoController.php(1160): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord('106')
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-01-20 16:33:39 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Operand should contain 1 column(s)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (39,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390819))')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (39,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390819))')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (:id_otros_t:, :detalle_act_otros_tit:, :fecha:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\NuevoController.php(1160): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord('106')
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-01-20 16:33:39 --> [Caused by] mysqli_sql_exception: Operand should contain 1 column(s)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (39,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390819))', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (39,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390819))')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (39,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390819))')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (:id_otros_t:, :detalle_act_otros_tit:, :fecha:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\NuevoController.php(1160): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord('106')
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-01-20 16:33:39 --> mysqli_sql_exception: Operand should contain 1 column(s) in C:\xampp\htdocs\valoradorG2\valorador\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\valoradorG2\valorador\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `ac...', 0)
#1 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ac...')
#2 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ac...')
#3 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ac...', Array, false)
#4 C:\xampp\htdocs\valoradorG2\valorador\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\valoradorG2\valorador\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\valoradorG2\valorador\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\valoradorG2\valorador\app\Controllers\NuevoController.php(1160): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord('106')
#9 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
#10 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\valoradorG2\valorador\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2025-01-20 16:33:39 --> CodeIgniter\Database\Exceptions\DatabaseException: Operand should contain 1 column(s)
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (:id_otros_t:, :detalle_act_otros_tit:, :fecha:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\NuevoController.php(1160): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord('106')
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-01-20 16:33:39 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Operand should contain 1 column(s)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (39,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390819))')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (39,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390819))')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (:id_otros_t:, :detalle_act_otros_tit:, :fecha:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\NuevoController.php(1160): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord('106')
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-01-20 16:33:39 --> [Caused by] mysqli_sql_exception: Operand should contain 1 column(s)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (39,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390819))', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (39,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390819))')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (39,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390819))')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (:id_otros_t:, :detalle_act_otros_tit:, :fecha:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\NuevoController.php(1160): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord('106')
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-01-20 16:33:39 --> mysqli_sql_exception: Operand should contain 1 column(s) in C:\xampp\htdocs\valoradorG2\valorador\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\valoradorG2\valorador\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `ac...', 0)
#1 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ac...')
#2 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ac...')
#3 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ac...', Array, false)
#4 C:\xampp\htdocs\valoradorG2\valorador\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\valoradorG2\valorador\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\valoradorG2\valorador\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\valoradorG2\valorador\app\Controllers\NuevoController.php(1160): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord('106')
#9 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
#10 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\valoradorG2\valorador\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2025-01-20 16:33:39 --> CodeIgniter\Database\Exceptions\DatabaseException: Operand should contain 1 column(s)
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (:id_otros_t:, :detalle_act_otros_tit:, :fecha:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\NuevoController.php(1160): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord('106')
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-01-20 16:33:39 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Operand should contain 1 column(s)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (39,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390819))')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (39,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390819))')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (:id_otros_t:, :detalle_act_otros_tit:, :fecha:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\NuevoController.php(1160): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord('106')
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-01-20 16:33:39 --> [Caused by] mysqli_sql_exception: Operand should contain 1 column(s)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (39,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390819))', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (39,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390819))')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (39,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390819))')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (:id_otros_t:, :detalle_act_otros_tit:, :fecha:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\NuevoController.php(1160): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord('106')
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-01-20 16:33:40 --> mysqli_sql_exception: Operand should contain 1 column(s) in C:\xampp\htdocs\valoradorG2\valorador\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\valoradorG2\valorador\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `ac...', 0)
#1 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ac...')
#2 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ac...')
#3 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ac...', Array, false)
#4 C:\xampp\htdocs\valoradorG2\valorador\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\valoradorG2\valorador\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\valoradorG2\valorador\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\valoradorG2\valorador\app\Controllers\NuevoController.php(1160): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord('106')
#9 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
#10 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\valoradorG2\valorador\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2025-01-20 16:33:40 --> CodeIgniter\Database\Exceptions\DatabaseException: Operand should contain 1 column(s)
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (:id_otros_t:, :detalle_act_otros_tit:, :fecha:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\NuevoController.php(1160): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord('106')
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-01-20 16:33:40 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Operand should contain 1 column(s)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (40,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390820))')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (40,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390820))')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (:id_otros_t:, :detalle_act_otros_tit:, :fecha:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\NuevoController.php(1160): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord('106')
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-01-20 16:33:40 --> [Caused by] mysqli_sql_exception: Operand should contain 1 column(s)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (40,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390820))', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (40,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390820))')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (40,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390820))')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (:id_otros_t:, :detalle_act_otros_tit:, :fecha:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\NuevoController.php(1160): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord('106')
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-01-20 16:33:40 --> mysqli_sql_exception: Operand should contain 1 column(s) in C:\xampp\htdocs\valoradorG2\valorador\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\valoradorG2\valorador\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `ac...', 0)
#1 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ac...')
#2 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ac...')
#3 C:\xampp\htdocs\valoradorG2\valorador\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ac...', Array, false)
#4 C:\xampp\htdocs\valoradorG2\valorador\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\valoradorG2\valorador\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\valoradorG2\valorador\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\valoradorG2\valorador\app\Controllers\NuevoController.php(1160): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord('106')
#9 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
#10 C:\xampp\htdocs\valoradorG2\valorador\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\valoradorG2\valorador\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2025-01-20 16:33:40 --> CodeIgniter\Database\Exceptions\DatabaseException: Operand should contain 1 column(s)
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (:id_otros_t:, :detalle_act_otros_tit:, :fecha:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\NuevoController.php(1160): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord('106')
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-01-20 16:33:40 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Operand should contain 1 column(s)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (40,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390820))')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (40,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390820))')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (:id_otros_t:, :detalle_act_otros_tit:, :fecha:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\NuevoController.php(1160): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord('106')
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2025-01-20 16:33:40 --> [Caused by] mysqli_sql_exception: Operand should contain 1 column(s)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (40,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390820))', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (40,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390820))')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (\'106\', \'diplomatura en ciberseguridad 2025-2-2\', (40,33,16,20,1,1,2025,19,\'Monday\',\'January\',1737390820))')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `actualizacion_otros_titulos` (`id_otros_t`, `detalle_act_otros_tit`, `fecha`) VALUES (:id_otros_t:, :detalle_act_otros_tit:, :fecha:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\NuevoController.php(1160): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->editRecord('106')
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-01-20 17:23:54 --> Registro con ID 102 no encontrado.
INFO - 2025-01-20 17:50:28 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-01-20 17:50:29 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-01-20 17:50:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-01-20 17:50:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-01-20 17:50:36 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-01-20 17:50:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-01-20 17:53:34 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-01-20 17:53:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-01-20 17:53:46 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-01-20 18:13:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-01-20 18:13:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-01-20 18:14:16 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2025-01-20 18:14:22 --> ErrorException: Undefined variable $titulo
in APPPATH\Controllers\NuevoController.php on line 737.
 1 APPPATH\Controllers\NuevoController.php(737): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $titulo', 'C:\\xampp\\htdocs\\valoradorG2\\valorador\\app\\Controllers\\NuevoController.php', 737)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\NuevoController->mostrar_valoraciones_porDocente_porMateria3()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\NuevoController))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
DEBUG - 2025-01-20 18:15:03 --> {"id_ant_doc":"107","detalle_ant_doc":"esc etoa","cantidad":"6","id_valoracion":"307","id_detalle_doc":"1"}
INFO - 2025-01-20 18:15:29 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-01-20 18:15:50 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2025-01-20 18:15:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
